name: Deploy Worker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Wrangler version
        run: npx wrangler --version

      - name: Authenticate (env for CI)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler whoami

      - name: Set Worker secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
            npx wrangler secret put TIKTOK_CLIENT_KEY        --name r2-tiktok-upload --text "${{ secrets.TIKTOK_CLIENT_KEY }}"
            npx wrangler secret put TIKTOK_CLIENT_SECRET     --name r2-tiktok-upload --text "${{ secrets.TIKTOK_CLIENT_SECRET }}"
            npx wrangler secret put OAUTH_REDIRECT_URL       --name r2-tiktok-upload --text "${{ secrets.OAUTH_REDIRECT_URL }}"
            npx wrangler secret put POST_API_KEY             --name r2-tiktok-upload --text "${{ secrets.POST_API_KEY }}"
            npx wrangler secret put R2_ACCESS_KEY_ID         --name r2-tiktok-upload --text "${{ secrets.R2_ACCESS_KEY_ID }}"
            npx wrangler secret put R2_SECRET_ACCESS_KEY     --name r2-tiktok-upload --text "${{ secrets.R2_SECRET_ACCESS_KEY }}"

      - name: Deploy
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler deploy --minify