name: Deploy Worker
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'wrangler.toml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Show Wrangler version
        run: npx wrangler --version

      - name: Auth check
        env:
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          echo "Account: $CLOUDFLARE_ACCOUNT_ID"
          test -n "$CLOUDFLARE_API_TOKEN" || (echo "CF API token missing" && exit 1)
          npx wrangler whoami

      # Set secrets via STDIN (works on v3/v4)
      - name: Set Worker secrets
        env:
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          printf "%s" "${{ secrets.TIKTOK_CLIENT_KEY }}"    | npx wrangler secret put TIKTOK_CLIENT_KEY    --name r2-tiktok-upload --config wrangler.toml
          printf "%s" "${{ secrets.TIKTOK_CLIENT_SECRET }}" | npx wrangler secret put TIKTOK_CLIENT_SECRET --name r2-tiktok-upload --config wrangler.toml
          printf "%s" "${{ secrets.OAUTH_REDIRECT_URL }}"   | npx wrangler secret put OAUTH_REDIRECT_URL   --name r2-tiktok-upload --config wrangler.toml
          printf "%s" "${{ secrets.POST_API_KEY }}"         | npx wrangler secret put POST_API_KEY         --name r2-tiktok-upload --config wrangler.toml
          printf "%s" "${{ secrets.R2_ACCESS_KEY_ID }}"     | npx wrangler secret put R2_ACCESS_KEY_ID     --name r2-tiktok-upload --config wrangler.toml
          printf "%s" "${{ secrets.R2_SECRET_ACCESS_KEY }}" | npx wrangler secret put R2_SECRET_ACCESS_KEY --name r2-tiktok-upload --config wrangler.toml

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler deploy --minify --config wrangler.toml --name r2-tiktok-upload