name: Deploy Worker
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: show wrangler version
      - run: npx wrangler --version

      # Set secrets (v4 supports --text)
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            secret put TIKTOK_CLIENT_KEY    --name r2-tiktok-upload --text "${{ secrets.TIKTOK_CLIENT_KEY }}"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            secret put TIKTOK_CLIENT_SECRET --name r2-tiktok-upload --text "${{ secrets.TIKTOK_CLIENT_SECRET }}"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            secret put OAUTH_REDIRECT_URL   --name r2-tiktok-upload --text "${{ secrets.OAUTH_REDIRECT_URL }}"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            secret put POST_API_KEY         --name r2-tiktok-upload --text "${{ secrets.POST_API_KEY }}"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            secret put R2_ACCESS_KEY_ID     --name r2-tiktok-upload --text "${{ secrets.R2_ACCESS_KEY_ID }}"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            secret put R2_SECRET_ACCESS_KEY --name r2-tiktok-upload --text "${{ secrets.R2_SECRET_ACCESS_KEY }}"

      # Finally: deploy
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --minify