name: Deploy Worker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      # Push Worker secrets to Cloudflare
      - name: Set Worker secrets
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
            printf "%s" "${{ secrets.TIKTOK_CLIENT_KEY }}"        | npx wrangler secret put TIKTOK_CLIENT_KEY        --config wrangler.toml --name r2-tiktok-upload
            printf "%s" "${{ secrets.TIKTOK_CLIENT_SECRET }}"     | npx wrangler secret put TIKTOK_CLIENT_SECRET     --config wrangler.toml --name r2-tiktok-upload
            printf "%s" "${{ secrets.OAUTH_REDIRECT_URL }}"       | npx wrangler secret put OAUTH_REDIRECT_URL       --config wrangler.toml --name r2-tiktok-upload
            printf "%s" "${{ secrets.POST_API_KEY }}"             | npx wrangler secret put POST_API_KEY             --config wrangler.toml --name r2-tiktok-upload
            printf "%s" "${{ secrets.R2_ACCESS_KEY_ID }}"         | npx wrangler secret put R2_ACCESS_KEY_ID         --config wrangler.toml --name r2-tiktok-upload
            printf "%s" "${{ secrets.R2_SECRET_ACCESS_KEY }}"     | npx wrangler secret put R2_SECRET_ACCESS_KEY     --config wrangler.toml --name r2-tiktok-upload

      - name: Deploy
        run: npx wrangler deploy --minify --config wrangler.toml --name r2-tiktok-upload