name: KV Inspect
on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      KV_NS_ID:              ${{ secrets.KV_NS_ID_TOKENS }}   # <-- prod namespace id
      KV_NS_ID_PREVIEW:      ${{ secrets.KV_NS_ID_TOKENS_PREVIEW || '' }}  # optional
    steps:
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Wrangler version
        run: npx wrangler@latest --version

      - name: List KV namespaces (sanity check)
        run: npx wrangler@latest kv namespace list

      - name: Try listing keys (PROD, no prefix)
        run: npx wrangler@latest kv key list --namespace-id "$KV_NS_ID" | head -n 200

      - name: Try listing keys (PROD, with 'api:' prefix)
        run: npx wrangler@latest kv key list --namespace-id "$KV_NS_ID" --prefix "api:" | head -n 200

      - name: Try listing keys (PREVIEW, if provided)
        if: env.KV_NS_ID_PREVIEW != ''
        run: |
          echo "Preview namespace: $KV_NS_ID_PREVIEW"
          npx wrangler@latest kv key list --namespace-id "$KV_NS_ID_PREVIEW" | head -n 200
          npx wrangler@latest kv key list --namespace-id "$KV_NS_ID_PREVIEW" --prefix "api:" | head -n 200