name: KV Inspect
on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN:   ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:  ${{ secrets.CF_ACCOUNT_ID }}
      KV_NS_ID:       ${{ secrets.KV_NS_ID_TOKENS }}
    steps:
      - name: Show inputs
        run: |
          echo "Account: $CF_ACCOUNT_ID"
          echo "Namespace: $KV_NS_ID"
      - name: List namespaces (sanity)
        run: |
          curl -sS -H "Authorization: Bearer $CF_API_TOKEN" \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces" | jq .
      - name: List ALL keys (first 200) for this namespace
        run: |
          curl -sS -H "Authorization: Bearer $CF_API_TOKEN" \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces/$KV_NS_ID/keys?limit=200" | jq .
      - name: List api:* keys (first 200)
        run: |
          curl -sS -H "Authorization: Bearer $CF_API_TOKEN" \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces/$KV_NS_ID/keys?prefix=api%3A&limit=200" | jq .