name: Purge ALL API Tokens
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Preview only (true = don't delete)"
        required: true
        default: "true"

jobs:
  purge_all:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      KV_NS_ID: ${{ secrets.KV_NS_ID_TOKENS }}
      DRY_RUN: ${{ github.event.inputs.dry_run }}
    steps:
      - name: Purge all api:* keys
        shell: bash
        run: |
          set -euo pipefail

          echo "Namespace: $KV_NS_ID"
          echo "Dry run: $DRY_RUN"

          keys=$(curl -sS -H "Authorization: Bearer $CF_API_TOKEN" \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces/$KV_NS_ID/keys?prefix=api%3A&limit=1000" \
            | jq -r '.result[].name')

          if [ -z "${keys:-}" ]; then
            echo "No api:* keys found."
            exit 0
          fi

          echo "Found $(printf '%s\n' "$keys" | wc -l) keys."
          printf '%s\n' "$keys"

          if [ "$DRY_RUN" = "true" ]; then
            echo "Dry run mode: skipping delete."
            exit 0
          fi

          echo "Deleting..."
          for key in $keys; do
            echo "Deleting $key"
            curl -sS -X DELETE -H "Authorization: Bearer $CF_API_TOKEN" \
              "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces/$KV_NS_ID/values/$key" \
              >/dev/null
          done

          echo "Done."