name: Purge ALL API tokens (api:*)
on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      BINDING: TOKENS_KV
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Wrangler version
        run: npx wrangler@latest --version

      - name: List and delete all api:* keys
        shell: bash
        run: |
          set -euo pipefail
          echo "Fetching keys from KV binding: $BINDING"
          keys=$(npx wrangler kv:key list --binding "$BINDING" \
            | jq -r '.[] | select(.name|startswith("api:")) | .name')

          if [ -z "$keys" ]; then
            echo "No api:* keys found."
            exit 0
          fi

          echo "Deleting the following keys:"
          printf '%s\n' "$keys"

          # Delete
          while IFS= read -r key; do
            npx wrangler kv:key delete "$key" --binding "$BINDING"
          done <<< "$keys"

          echo "Done. Purged $(printf '%s\n' "$keys" | wc -l) api:* keys."