name: Purge API tokens (pending and/or unmatched)
on:
  workflow_dispatch:
    inputs:
      purge_pending:
        description: "Delete tokens with status=pending"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
      purge_unmatched:
        description: "Delete active tokens whose open_id has no tok:open:<open_id>"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
      dry_run:
        description: "Dry run (show what would be deleted, but don't delete)"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]

jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      BINDING: TOKENS_KV
      DO_PENDING:   ${{ github.event.inputs.purge_pending }}
      DO_UNMATCHED: ${{ github.event.inputs.purge_unmatched }}
      DRY_RUN:      ${{ github.event.inputs.dry_run }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Wrangler version
        run: npx wrangler@latest --version

      - name: Scan and (maybe) delete
        shell: bash
        run: |
          set -euo pipefail

          echo "Binding: $BINDING"
          echo "Options: purge_pending=$DO_PENDING, purge_unmatched=$DO_UNMATCHED, dry_run=$DRY_RUN"

          # Get all api:* keys
          api_keys=$(npx wrangler kv:key list --binding "$BINDING" \
            | jq -r '.[] | select(.name|startswith("api:")) | .name')

          if [ -z "$api_keys" ]; then
            echo "No api:* keys found."
            exit 0
          fi

          to_delete=""

          while IFS= read -r key; do
            [ -z "$key" ] && continue
            v=$(npx wrangler kv:key get "$key" --binding "$BINDING" || true)
            # Skip if no value (already deleted or empty)
            [ -z "$v" ] && continue

            status=$(echo "$v" | jq -r '.status // empty')
            open_id=$(echo "$v" | jq -r '.open_id // empty')

            # Pending?
            if [ "$DO_PENDING" = "true" ] && [ "$status" = "pending" ]; then
              to_delete+="$key"$'\n'
              continue
            fi

            # Unmatched active? (active but no tok:open:<open_id>)
            if [ "$DO_UNMATCHED" = "true" ] && [ "$status" = "active" ] && [ -n "$open_id" ]; then
              tok_key="tok:open:$open_id"
              tok_val=$(npx wrangler kv:key get "$tok_key" --binding "$BINDING" || true)
              if [ -z "$tok_val" ]; then
                to_delete+="$key"$'\n'
              fi
            fi
          done <<< "$api_keys"

          if [ -z "$to_delete" ]; then
            echo "Nothing to delete under the given criteria."
            exit 0
          fi

          echo "Keys to delete:"
          printf '%s\n' "$to_delete"

          if [ "$DRY_RUN" = "true" ]; then
            echo "Dry run enabled. Not deleting."
            exit 0
          fi

          echo "Deleting..."
          while IFS= read -r key; do
            [ -z "$key" ] && continue
            npx wrangler kv:key delete "$key" --binding "$BINDING"
          done <<< "$to_delete"

          echo "Done."