name: Purge ALL API tokens (api:*)
on:
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      KV_NS_ID:              ${{ secrets.KV_NS_ID_TOKENS }}
    steps:
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Wrangler version
        run: npx wrangler@latest --version

      - name: List and delete all api:* keys
        shell: bash
        run: |
          set -euo pipefail

          echo "Listing api:* from namespace: $KV_NS_ID"
          keys=$(npx wrangler@latest kv:key list \
            --namespace-id "$KV_NS_ID" \
            --prefix "api:" | jq -r '.[].name')

          if [ -z "${keys:-}" ]; then
            echo "No api:* keys found."
            exit 0
          fi

          echo "Deleting $(printf '%s\n' "$keys" | wc -l) keys…"
          while IFS= read -r key; do
            [ -z "$key" ] && continue
            npx wrangler@latest kv:key delete "$key" --namespace-id "$KV_NS_ID"
          done <<< "$keys"

          echo "Done."